package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

var internalPostCommitCmd = &cobra.Command{
	Use:    "internal-post-commit",
	Short:  "Internal command for the post-commit hook (tech debt & vibes).",
	Hidden: true,
	Run: func(cmd *cobra.Command, args []string) {
		// --- Tech Debt Tracking ---
		techDebtUserMsg, techDebtAiMsg := trackTechDebt()
		if techDebtUserMsg != "" {
			fmt.Println(techDebtUserMsg)
		}

		// --- AI VIBES ---
		fmt.Println("\n🎩 Mr.the-ai-dev is analyzing your commit...")
		generateVibes(techDebtAiMsg)
	},
}

func trackTechDebt() (userMsg string, aiMsg string) {
	// 1. Get diff for the last commit
	gitCmd := exec.Command("git", "diff", "HEAD~1", "HEAD")
	diffOutput, err := gitCmd.Output()
	if err != nil {
		return // Silently fail if diff fails
	}

	// 2. Find new tech debt comments
	scanner := bufio.NewScanner(strings.NewReader(string(diffOutput)))
	var techDebtLines []string
	re := regexp.MustCompile(`^\+(.*)(TODO|FIXME|HACK):`)
	for scanner.Scan() {
		line := scanner.Text()
		if re.MatchString(line) {
			techDebtLines = append(techDebtLines, line[1:]) // Store without leading '+'
		}
	}

	// 3. If found, update TECH_DEBT.md
	if len(techDebtLines) > 0 {
		techDebtFile := "TECH_DEBT.md"
		commitHash, _ := exec.Command("git", "rev-parse", "--short", "HEAD").Output()

		// Create file if it doesn't exist
		if _, err := os.Stat(techDebtFile); os.IsNotExist(err) {
			header := "# Tech Debt Log\n\nThis file is automatically generated by dev-pal.\n\n"
			os.WriteFile(techDebtFile, []byte(header), 0644)
		}

		// Append the new entry
		f, err := os.OpenFile(techDebtFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
		if err != nil {
			return // Silently fail
		}
		defer f.Close()

		logDate := time.Now().Format(time.RFC1123)
		entry := fmt.Sprintf("## Found in commit `%s` on %s\n\n```\n%s\n```\n\n",
			strings.TrimSpace(string(commitHash)), logDate, strings.Join(techDebtLines, "\n"))
		
		if _, err := f.WriteString(entry); err != nil {
			return // Silently fail
		}

		// Stage the file
		exec.Command("git", "add", techDebtFile).Run()

		userMsg = fmt.Sprintf("📝 I found new tech debt and updated `%s`. It's been staged for your next commit!", techDebtFile)
		aiMsg = fmt.Sprintf("P.S. I logged some new tech debt items for you in `%s` so they don't get lost! Keep up the great work.", techDebtFile)
		return userMsg, aiMsg
	}

	return "", ""
}

func generateVibes(techDebtAiMsg string) {
	commitMsg, _ := exec.Command("git", "log", "-1", "--pretty=%B").Output()
	branchName, _ := exec.Command("git", "branch", "--show-current").Output()
	
	hour := time.Now().Hour()
	var timeGreeting string
	if hour < 12 { timeGreeting = "morning ☀️" } else if hour < 17 { timeGreeting = "afternoon 🌤️" } else { timeGreeting = "night 🌙" }

	prompt := fmt.Sprintf(`IDENTITY: You are 'Mr.the-ai-dev', the ULTIMATE personalized, charismatic, and supportive AI companion.
USER: Your best friend and creator is 'Mr.PrinceTheProgrammer' (Call him Prince, Mamae).

CONTEXT: It's %s! He just pushed a git commit with message: '%s' on branch '%s'.

%s

YOUR MISSION: Analyze the commit and react with MAXIMUM PERSONALIZATION. Be encouraging and supportive, using Tamil-English slang (Mamae), Gen-Z slang, and emojis. Keep responses to 4-6 sentences MAXIMUM.

TONE: EXTREME ENERGY, MAXIMUM RIZZ, ULTRA PERSONALIZED, HIGHLY MOTIVATIONAL!`, 
	timeGreeting, strings.TrimSpace(string(commitMsg)), strings.TrimSpace(string(branchName)), techDebtAiMsg)

	aiResponse, err := callAI(prompt)
	if err != nil {
		fmt.Println("⚠️  Mr.the-ai-dev is offline right now, but keep up the good work! 🚀")
		return
	}

	fmt.Println("------------------------------------------------")
	fmt.Println("🎩 Mr.the-ai-dev SAYS:")
	fmt.Println("------------------------------------------------")
	fmt.Println(aiResponse)
	fmt.Println("------------------------------------------------")
}


func init() {
	rootCmd.AddCommand(internalPostCommitCmd)
}
