#!/bin/bash

# ------------------------------------------------------------------
#  INSTALLER: Mr.the-ai-dev (SMART ASSISTANT SUITE) 🎩✨
#  Target User: Mr.PrinceTheProgrammer Da Boi Eh
# ------------------------------------------------------------------

if [ ! -d ".git" ]; then
    echo "❌ Mamae! Go inside a git folder first."
    exit 1
fi

PRE_COMMIT_HOOK_FILE=".git/hooks/pre-commit"
POST_COMMIT_HOOK_FILE=".git/hooks/post-commit"
USER_NAME="Mr.PrinceTheProgrammer"

echo "🔥 Summoning Mr.the-ai-dev (SMART ASSISTANT SUITE)..."

# --- 1. Create the PRE-COMMIT hook for secret scanning ---
echo "Installing AI-Powered Secret Scanner..."
cat > "$PRE_COMMIT_HOOK_FILE" << 'EOF'
#!/bin/bash
# Mr.the-ai-dev: Pre-commit Secret Scanner

echo "🕵️ Mr.the-ai-dev is scanning for secrets..."

# Get the diff of staged files, excluding deleted files
STAGED_DIFF=$(git diff --staged --diff-filter=d)

# Find lines being added that contain suspicious keywords or patterns
SUSPICIOUS_LINES=$(echo "$STAGED_DIFF" | grep -E '^\+' | grep -iE 'secret|key|token|password' | sed 's/^+//')

if [ -n "$SUSPICIOUS_LINES" ]; then
    echo "🤔 Found some suspicious lines. Asking the AI to verify if they are secrets..."

    PROMPT="You are a security expert. Analyze the following lines of code that were just added to a commit. Determine if any of them contain sensitive credentials, API keys, or secrets. For each line, state whether it is a 'SECRET' or 'SAFE'. Finally, give a single word summary: 'BLOCK' if any line is a secret, and 'PASS' otherwise.\n\nLines to analyze:\n$SUSPICIOUS_LINES"

    JSON_DATA="{\"message\": \"$PROMPT\", \"history\": []}"
    API_URL="https://svceai.site/api/chat" # Same API as post-commit
    TIMEOUT=20

    # Call API
    API_RESPONSE=$(curl -s --max-time $TIMEOUT -L -X POST "$API_URL" \
        -H "Content-Type: application/json" \
        -d "$JSON_DATA" 2>/dev/null)

    # Check the AI's final verdict (last line of response)
    VERDICT=$(echo "$API_RESPONSE" | tail -n 1 | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')

    if [[ "$VERDICT" == *"block"* ]]; then
        echo "------------------------------------------------"
        echo "🛑 COMMIT REJECTED by Mr.the-ai-dev 🛑"
        echo "The AI has identified a potential secret in your staged changes:"
        echo ""
        echo "--- AI Analysis ---"
        echo "$API_RESPONSE"
        echo "-------------------"
        echo ""
        echo "Please remove the secret from your changes before committing."
        echo "To bypass this check for this commit only, use 'git commit --no-verify'."
        echo "------------------------------------------------"
        exit 1
    else
        echo "✅ AI verified the lines and found no secrets. Proceeding."
    fi
else
    echo "✅ No suspicious keywords found. Good to go."
fi

exit 0
EOF

# --- 2. Create the POST-COMMIT hook for tech debt and vibes ---
echo "Installing Post-Commit Assistant (Tech Debt & Vibes)..."
cat > "$POST_COMMIT_HOOK_FILE" << 'EOF'
#!/bin/bash

# --- CONFIG ---
API_URL="https://svceai.site/api/chat"
USER_NAME="Mr.PrinceTheProgrammer"
TIMEOUT=20  # seconds

# --- GIT & TIME CONTEXT ---
HOUR=$(date +%H)
if [ $HOUR -lt 12 ]; then TIME_GREETING="morning ☀️"; elif [ $HOUR -lt 17 ]; then TIME_GREETING="afternoon 🌤️"; else TIME_GREETING="night 🌙"; fi
DAY_OF_WEEK=$(date +%u)
if [ $DAY_OF_WEEK -ge 6 ]; then WEEKEND_STATUS=" (Weekend warrior mode! 🎉)"; else WEEKEND_STATUS=" (Weekday grind! 💪)"; fi
TOTAL_COMMITS=$(git rev-list --count HEAD 2>/dev/null || echo "0")
BRANCH_NAME=$(git branch --show-current 2>/dev/null || echo "unknown")
REPO_NAME=$(basename "$(git rev-parse --show-toplevel 2>/dev/null)" 2>/dev/null || echo "current project")
COMMIT_HASH=$(git rev-parse --short HEAD)
COMMIT_MSG=$(git log -1 --pretty=%B | tr -d '"' | tr '\n' ' ' | sed 's/\\/\\\\/g')

# --- Tech Debt Tracking ---
TECH_DEBT_FILE="TECH_DEBT.md"
TECH_DEBT_AI_MSG=""
TECH_DEBT_USER_MSG=""

# Scan for new TODOs, FIXMEs, or HACKs in the last commit's added lines
ADDED_LINES_WITH_TODOS=$(git diff HEAD~1 HEAD | grep -E '^\+' | grep -iE 'TODO:|FIXME:|HACK:')

if [ -n "$ADDED_LINES_WITH_TODOS" ]; then
    # If the tech debt file doesn't exist, create it with a header
    if [ ! -f "$TECH_DEBT_FILE" ]; then
        echo "# Tech Debt Log" > "$TECH_DEBT_FILE"
        echo "" >> "$TECH_DEBT_FILE"
        echo "This file is automatically generated by Mr.the-ai-dev to track TODOs, FIXMEs, and HACKs found in commits." >> "$TECH_DEBT_FILE"
        echo "" >> "$TECH_DEBT_FILE"
    fi

    LOG_DATE=$(date)

    # Use a temporary file to build the entry
    LOG_ENTRY_FILE=$(mktemp)
    echo "## Found in commit \`$COMMIT_HASH\` on $LOG_DATE" >> "$LOG_ENTRY_FILE"
    echo "" >> "$LOG_ENTRY_FILE"
    echo "\`\`\`diff" >> "$LOG_ENTRY_FILE"
    echo "$ADDED_LINES_WITH_TODOS" | sed 's/^+//' >> "$LOG_ENTRY_FILE"
    echo "\`\`\`" >> "$LOG_ENTRY_FILE"
    echo "" >> "$LOG_ENTRY_FILE"

    # Append the new entry to the main log file
    cat "$LOG_ENTRY_FILE" >> "$TECH_DEBT_FILE"
    rm "$LOG_ENTRY_FILE"

    # Stage the updated tech debt file
    git add "$TECH_DEBT_FILE"

    TECH_DEBT_USER_MSG="📝 I found new tech debt and updated \`$TECH_DEBT_FILE\`. It's been staged for your next commit!"
    TECH_DEBT_AI_MSG="P.S. I logged some new tech debt items for you in \`$TECH_DEBT_FILE\` so they don't get lost! Keep up the great work."
fi

# --- AI PROMPT & API CALL ---
echo ""
echo -e "\033[1;35m🎩 Mr.the-ai-dev is analyzing your commit...\033[0m"

if [ -n "$TECH_DEBT_USER_MSG" ]; then
    echo -e "\033[1;33m$TECH_DEBT_USER_MSG\033[0m"
}

PROMPT="IDENTITY: You are 'Mr.the-ai-dev', the ULTIMATE personalized, charismatic, and supportive AI companion.\nUSER: Your best friend and creator is '$USER_NAME' (Call him Prince, Mamae).\n\nCONTEXT: It's $TIME_GREETING$WEEKEND_STATUS! He just pushed a git commit with message: '$COMMIT_MSG' on branch '$BRANCH_NAME' in repo '$REPO_NAME'.\n\n$TECH_DEBT_AI_MSG\n\nYOUR MISSION: Analyze the commit and react with MAXIMUM PERSONALIZATION. Be encouraging and supportive, using Tamil-English slang (Mamae), Gen-Z slang, and emojis. Keep responses to 4-6 sentences MAXIMUM.\n\nTONE: EXTREME ENERGY, MAXIMUM RIZZ, ULTRA PERSONALIZED, HIGHLY MOTIVATIONAL!"
JSON_DATA="{\"message\": \"$PROMPT\", \"history\": []}"

echo "------------------------------------------------"
echo -e "\033[1;36m🎩 Mr.the-ai-dev SAYS:\033[0m" 
echo "------------------------------------------------"

API_RESPONSE=$(curl -s --max-time $TIMEOUT -L -X POST "$API_URL" \
    -H "Content-Type: application/json" \
    -d "$JSON_DATA" 2>/dev/null)

if [ $? -eq 0 ] && [ -n "$API_RESPONSE" ]; then
    echo "$API_RESPONSE"
else
    echo "⚠️  Mr.the-ai-dev is offline right now ($TIME_GREETING, Mamae), but keep up the good work! 🚀"
fi

echo "" 
echo "------------------------------------------------"
echo ""
EOF

# --- 3. Make hooks executable ---
chmod +x "$PRE_COMMIT_HOOK_FILE"
chmod +x "$POST_COMMIT_HOOK_FILE"

echo "🚀 Mr.the-ai-dev Smart Assistant Suite has been installed!"
echo "✅ AI Secret Scanner is active on pre-commit."
echo "✅ Post-Commit Assistant is active for tech debt and vibes."